# Generated by Django 6.0.5 on 2026-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anonymoustip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustip',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='anonymoustip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustip',
            name='risk_level',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
