# Generated by Django 5.2.6 on 2026-08-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anonymoustip_category_anonymoustip_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mulealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='evidence',
            name='deepfake_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidence',
            name='deepfake_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='evidence',
            name='is_deepfake',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
