# Generated by Django 5.2.6 on 2026-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mulealert_options_evidence_deepfake_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='urgency_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='duress_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('supervisor', 'Supervisor'), ('secret_agent', 'Secret Agent'), ('admin', 'System Admin')], db_index=True, default='citizen', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-urgency_score'], name='api_complai_status_f589e3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category', '-created_at'], name='api_complai_categor_0a0fa4_idx'),
        ),
    ]
