# Generated by Django 5.2.6 on 2026-08-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(db_index=True, default='Ahmedabad', max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('jurisdiction', models.CharField(max_length=150)),
                ('is_cyber_specialized', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('officer_capacity', models.IntegerField(default=10)),
                ('active_cases', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assignment_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='detected_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.CharField(db_index=True, default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_score', models.FloatField(default=0.0)),
                ('specialization_score', models.FloatField(default=0.0)),
                ('workload_score', models.FloatField(default=0.0)),
                ('proximity_km', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_records', to='api.complaint')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.policestation')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='api.policestation'),
        ),
    ]
