# Generated by Django 5.2.6 on 2026-08-17 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_policestation_complaint_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='Class A', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('progress', models.IntegerField(default=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.policestation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
