# Generated by Django 5.2.6 on 2026-08-18 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('pending', 'Pending'), ('investigating', 'Investigating'), ('under_investigation', 'Under Investigation'), ('evidence_review', 'Evidence Review'), ('supervisor_review', 'Supervisor Review'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CanonicalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('phone', 'Phone'), ('upi', 'UPI ID'), ('email', 'Email'), ('domain', 'Domain/URL'), ('account', 'Bank Account')], db_index=True, max_length=20)),
                ('original_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=255)),
                ('risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_entities', to='api.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('investigation', 'Investigation'), ('evidence', 'Evidence'), ('financial', 'Financial'), ('legal', 'Legal'), ('supervisor', 'Supervisor')], default='investigation', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_notes', to='api.complaint')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.complaint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entity', models.CharField(db_index=True, max_length=255)),
                ('target_entity', models.CharField(db_index=True, max_length=255)),
                ('relationship_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('verification_status', models.CharField(choices=[('reported', 'User Reported'), ('ai_inferred', 'AI Inferred'), ('verified', 'Verified'), ('dismissed', 'Dismissed')], default='reported', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_relations', to='api.complaint')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
