import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_investigation_pdf(complaint, user) -> bytes:
    """Generate official downloadable Investigation Report PDF using ReportLab."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#0f172a'),
        alignment=0
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#2563eb'),
        alignment=0
    )
    
    h2_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=10,
        spaceAfter=4
    )
    
    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155')
    )

    mono_style = ParagraphStyle(
        'MonoText',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#0f172a')
    )

    story = []

    # Title & Header
    story.append(Paragraph("SMARTPOL AI — OFFICIAL INVESTIGATION REPORT", title_style))
    story.append(Paragraph("AHMEDABAD POLICE CYBER CRIME COMMAND GRID | CONFIDENTIAL REPORT", subtitle_style))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563eb'), spaceBefore=2, spaceAfter=8))

    # Case Summary Table
    citizen_name = complaint.citizen.get_full_name() if complaint.citizen else "Anonymous/Citizen"
    officer_name = complaint.assigned_officer.get_full_name() if complaint.assigned_officer else "Unassigned"
    station_name = complaint.assigned_station.name if complaint.assigned_station else "Mithakhali Cyber Cell"

    summary_data = [
        [Paragraph("<b>CASE REFERENCE ID:</b>", body_style), Paragraph(f"<b>{complaint.complaint_id}</b>", body_style),
         Paragraph("<b>DATE FILED:</b>", body_style), Paragraph(complaint.created_at.strftime("%Y-%m-%d %H:%M"), body_style)],
        [Paragraph("<b>CRIME CATEGORY:</b>", body_style), Paragraph(complaint.category, body_style),
         Paragraph("<b>STATUS:</b>", body_style), Paragraph(complaint.status.replace("_", " ").upper(), body_style)],
        [Paragraph("<b>URGENCY SCORE:</b>", body_style), Paragraph(f"{int(complaint.urgency_score * 100)}%", body_style),
         Paragraph("<b>READINESS SCORE:</b>", body_style), Paragraph(f"{int(complaint.readiness_score * 100)}%", body_style)],
        [Paragraph("<b>ASSIGNED STATION:</b>", body_style), Paragraph(station_name, body_style),
         Paragraph("<b>INVESTIGATING OFFICER:</b>", body_style), Paragraph(officer_name, body_style)],
        [Paragraph("<b>REPORTING CITIZEN:</b>", body_style), Paragraph(citizen_name, body_style),
         Paragraph("<b>REPORT GENERATED BY:</b>", body_style), Paragraph(user.get_full_name() or user.username, body_style)],
    ]

    t_summary = Table(summary_data, colWidths=[1.5*inch, 2.0*inch, 1.5*inch, 2.0*inch])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 10))

    # Incident Description
    story.append(Paragraph("1. INCIDENT DESCRIPTION & REPORTED STATEMENT", h2_style))
    story.append(Paragraph(complaint.description, body_style))
    story.append(Spacer(1, 10))

    # Extracted Entities & Forensics
    story.append(Paragraph("2. AI TRIAGE & FORENSIC EVIDENCE VAULT", h2_style))
    entities = complaint.entities_extracted or {}
    ent_text = f"Phones: {', '.join(entities.get('phones', [])) or 'None'} | Emails: {', '.join(entities.get('emails', [])) or 'None'} | Amounts: {', '.join(entities.get('amounts', [])) or 'None'}"
    story.append(Paragraph(f"<b>Extracted Entities:</b> {ent_text}", body_style))
    story.append(Spacer(1, 6))

    evidence_list = complaint.evidence.all()
    if evidence_list.exists():
        ev_data = [[Paragraph("<b>File Name</b>", body_style), Paragraph("<b>Type</b>", body_style), Paragraph("<b>SHA-256 Hash Digest</b>", body_style), Paragraph("<b>Forensics Status</b>", body_style)]]
        for ev in evidence_list:
            deep_status = "🚨 Deepfake Flagged" if ev.is_deepfake else "Clean / Authentic"
            ev_data.append([
                Paragraph(ev.file_name[:25], body_style),
                Paragraph(ev.file_type, body_style),
                Paragraph(ev.hash_value[:18] + "...", mono_style),
                Paragraph(deep_status, body_style)
            ])
        t_ev = Table(ev_data, colWidths=[1.8*inch, 1.0*inch, 2.5*inch, 1.7*inch])
        t_ev.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e2e8f0')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t_ev)
    else:
        story.append(Paragraph("No physical/digital files attached to evidence vault.", body_style))

    story.append(Spacer(1, 10))

    # Investigator Tasks & Diary Notes
    story.append(Paragraph("3. INVESTIGATION TASKS & OFFICIAL CASE DIARY", h2_style))
    tasks = complaint.tasks.all()
    if tasks.exists():
        task_data = [[Paragraph("<b>Task Title</b>", body_style), Paragraph("<b>Priority</b>", body_style), Paragraph("<b>Status</b>", body_style)]]
        for tk in tasks:
            task_data.append([
                Paragraph(tk.title, body_style),
                Paragraph(tk.priority.upper(), body_style),
                Paragraph(tk.status.upper(), body_style)
            ])
        t_tk = Table(task_data, colWidths=[3.5*inch, 1.5*inch, 2.0*inch])
        t_tk.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t_tk)
    else:
        story.append(Paragraph("No active investigator tasks assigned.", body_style))

    story.append(Spacer(1, 10))

    # Section 91 CrPC Legal Notice Template
    story.append(Paragraph("4. LEGAL NOTICE TEMPLATE (SECTION 91 CrPC - BANK FREEZE)", h2_style))
    notice_text = (
        "<b>MEMORANDUM FOR BANK NODAL OFFICER / FINANCIAL INTERMEDIARY:</b><br/>"
        f"Notice is hereby issued under Section 91 CrPC regarding Case Ref <b>{complaint.complaint_id}</b>. "
        "You are hereby directed to immediately freeze and restrict debit transactions on all beneficiary accounts "
        "linked to this incident to prevent dissipation of cyber crime fraud proceeds."
    )
    story.append(Paragraph(notice_text, body_style))

    story.append(Spacer(1, 14))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#94a3b8'), spaceBefore=4, spaceAfter=8))
    
    footer_text = f"Official Record compiled at {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')} | Verification Stamp: SMARTPOL-AUTH-{complaint.id:06d}"
    story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=body_style, fontSize=7, textColor=colors.HexColor('#64748b'), alignment=1)))

    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data
