from django.core.management.base import BaseCommand
from api.models import PoliceStation

class Command(BaseCommand):
    help = 'Seeds complete dataset of 53 Ahmedabad Police Stations and Cyber Cells across all urban zones.'

    def handle(self, *args, **options):
        stations_data = [
            # ── CYBER SPECIALIZED UNITS & CELLS (5) ──────────────────────────
            {
                'name': 'Mithakhali Cyber Crime Police Station',
                'district': 'Ahmedabad',
                'area': 'Mithakhali / Shahibaug',
                'latitude': 23.0333,
                'longitude': 72.5667,
                'jurisdiction': 'Ahmedabad Urban Cyber Jurisdiction (Entire City)',
                'is_cyber_specialized': True,
                'contact_number': '1930',
                'officer_capacity': 30,
                'status': 'active',
            },
            {
                'name': 'S.G. Highway Crime Branch Cyber Cell',
                'district': 'Ahmedabad',
                'area': 'SG Highway / Thaltej',
                'latitude': 23.0500,
                'longitude': 72.5050,
                'jurisdiction': 'SG Highway Corridor, Thaltej Cross Roads, Science City Circle',
                'is_cyber_specialized': True,
                'contact_number': '1930',
                'officer_capacity': 35,
                'status': 'active',
            },
            {
                'name': 'CID Crime Gujarat Cyber Cell',
                'district': 'Ahmedabad',
                'area': 'Koba Circle / Airport Road',
                'latitude': 23.1120,
                'longitude': 72.6100,
                'jurisdiction': 'State Level Financial & High Tech Cybercrime Unit',
                'is_cyber_specialized': True,
                'contact_number': '1930',
                'officer_capacity': 40,
                'status': 'active',
            },
            {
                'name': 'Ahmedabad East Cyber Crime Branch Unit',
                'district': 'Ahmedabad',
                'area': 'Nikol / Naroda',
                'latitude': 23.0550,
                'longitude': 72.6650,
                'jurisdiction': 'East Zone Cyber Crime & UPI Fraud Special Division',
                'is_cyber_specialized': True,
                'contact_number': '1930',
                'officer_capacity': 25,
                'status': 'active',
            },
            {
                'name': 'Ahmedabad South Cyber Intelligence Cell',
                'district': 'Ahmedabad',
                'area': 'Maninagar / Kankaria',
                'latitude': 22.9920,
                'longitude': 72.6010,
                'jurisdiction': 'South Zone Cyber Surveillance & Financial Fraud Unit',
                'is_cyber_specialized': True,
                'contact_number': '1930',
                'officer_capacity': 25,
                'status': 'active',
            },

            # ── WEST & CENTRAL ZONE POLICE STATIONS (20) ────────────────────
            {
                'name': 'Satellite Police Station',
                'district': 'Ahmedabad',
                'area': 'Satellite / Jodhpur',
                'latitude': 23.0298,
                'longitude': 72.5180,
                'jurisdiction': 'Satellite, Ramdev Nagar, Shyamal, Jodhpur Circle',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2685-1100',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Navrangpura Police Station',
                'district': 'Ahmedabad',
                'area': 'Navrangpura / CG Road',
                'latitude': 23.0372,
                'longitude': 72.5609,
                'jurisdiction': 'Navrangpura, Commerce Six Roads, CG Road, Commerce College',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2640-0200',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Vastrapur Police Station',
                'district': 'Ahmedabad',
                'area': 'Vastrapur / IIM Road',
                'latitude': 23.0375,
                'longitude': 72.5284,
                'jurisdiction': 'Vastrapur Lake, IIMA Campus, Gurukul, Helmet Circle',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2676-0300',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Anandnagar Police Station',
                'district': 'Ahmedabad',
                'area': 'Prahladnagar / Anandnagar',
                'latitude': 23.0120,
                'longitude': 72.5110,
                'jurisdiction': 'Corporate Road, Prahladnagar Garden, Venus Atlantis, Vejalpur West',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2693-0100',
                'officer_capacity': 22,
                'status': 'active',
            },
            {
                'name': 'Bodakdev Police Station',
                'district': 'Ahmedabad',
                'area': 'Bodakdev / Judges Bungalow',
                'latitude': 23.0410,
                'longitude': 72.5110,
                'jurisdiction': 'Bodakdev, Judges Bungalow Road, Sindhu Bhavan Road, Pakwan',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2687-0600',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Sola High Court Police Station',
                'district': 'Ahmedabad',
                'area': 'Sola / High Court',
                'latitude': 23.0780,
                'longitude': 72.5250,
                'jurisdiction': 'Gujarat High Court, Civil Hospital Sola, Science City Road North',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2766-0200',
                'officer_capacity': 25,
                'status': 'active',
            },
            {
                'name': 'Ghatlodia Police Station',
                'district': 'Ahmedabad',
                'area': 'Ghatlodia / KK Nagar',
                'latitude': 23.0640,
                'longitude': 72.5410,
                'jurisdiction': 'Ghatlodia, KK Nagar, Memnagar, Chanakyapuri Road',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2748-0300',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Naranpura Police Station',
                'district': 'Ahmedabad',
                'area': 'Naranpura / Ankur',
                'latitude': 23.0520,
                'longitude': 72.5550,
                'jurisdiction': 'Naranpura, Ankur Cross Roads, Vijay Nagar, AEC Char Rasta',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2745-0400',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Sabarmati Police Station',
                'district': 'Ahmedabad',
                'area': 'Sabarmati / RTO',
                'latitude': 23.0800,
                'longitude': 72.5800,
                'jurisdiction': 'Sabarmati, Ashram Road North, RTO Circle, Motera Stadium Rd',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2750-0700',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Chandkheda Police Station',
                'district': 'Ahmedabad',
                'area': 'Chandkheda / Motera',
                'latitude': 23.1050,
                'longitude': 72.5920,
                'jurisdiction': 'Narendra Modi Stadium, ONGC Campus, Visat Circle, Zundal Ring Road',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2770-0500',
                'officer_capacity': 24,
                'status': 'active',
            },
            {
                'name': 'Bopal Police Station',
                'district': 'Ahmedabad',
                'area': 'Bopal / South Bopal',
                'latitude': 23.0320,
                'longitude': 72.4670,
                'jurisdiction': 'Bopal, South Bopal, TRP Mall, Gala Gymkhana Road, Shela',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2970-0600',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Shela Police Station',
                'district': 'Ahmedabad',
                'area': 'Shela / Club O7',
                'latitude': 23.0180,
                'longitude': 72.4510,
                'jurisdiction': 'Shela Village, Club O7 Road, Vipul Dudhiya Circle',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2970-0700',
                'officer_capacity': 15,
                'status': 'active',
            },
            {
                'name': 'Shahibaug Police Station',
                'district': 'Ahmedabad',
                'area': 'Shahibaug / Cantonment',
                'latitude': 23.0560,
                'longitude': 72.5890,
                'jurisdiction': 'Shahibaug, Camp Road, Civil Hospital Complex, Subhash Bridge',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2286-0400',
                'officer_capacity': 22,
                'status': 'active',
            },
            {
                'name': 'Ellisbridge Police Station',
                'district': 'Ahmedabad',
                'area': 'Ellisbridge / VS Hospital',
                'latitude': 23.0210,
                'longitude': 72.5710,
                'jurisdiction': 'Ellisbridge, Town Hall, VS Hospital, Ashram Road South',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2657-0900',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Gujarat University Police Station',
                'district': 'Ahmedabad',
                'area': 'University Area',
                'latitude': 23.0360,
                'longitude': 72.5460,
                'jurisdiction': 'Gujarat University Campus, LD Engineering, CEPT Campus',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2630-0100',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Ranip Police Station',
                'district': 'Ahmedabad',
                'area': 'Ranip / New Ranip',
                'latitude': 23.0810,
                'longitude': 72.5690,
                'jurisdiction': 'Ranip, New Ranip, GST Crossing, Balol Nagar',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2752-0200',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Vejalpur Police Station',
                'district': 'Ahmedabad',
                'area': 'Vejalpur / Juhapura',
                'latitude': 23.0040,
                'longitude': 72.5290,
                'jurisdiction': 'Vejalpur Gam, Vishala Circle, Bakeri City, Juhapura North',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2682-0300',
                'officer_capacity': 22,
                'status': 'active',
            },
            {
                'name': 'Sarkhej Police Station',
                'district': 'Ahmedabad',
                'area': 'Sarkhej / Sanand Circle',
                'latitude': 22.9860,
                'longitude': 72.4980,
                'jurisdiction': 'Sarkhej Roza, Sanand Cross Road, Ujala Circle, Fatehwadi',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2689-0400',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Changodar Police Station',
                'district': 'Ahmedabad',
                'area': 'Changodar / GIDC',
                'latitude': 22.9280,
                'longitude': 72.4410,
                'jurisdiction': 'Changodar Industrial Zone, Moraiya, Bavla Highway',
                'is_cyber_specialized': False,
                'contact_number': '+91-2717-250100',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Mahila Police Station West',
                'district': 'Ahmedabad',
                'area': 'Karanj / Riverfront West',
                'latitude': 23.0250,
                'longitude': 72.5780,
                'jurisdiction': 'West Ahmedabad Women Protection & Counseling Cell',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2550-0100',
                'officer_capacity': 15,
                'status': 'active',
            },

            # ── EAST & NORTH ZONE POLICE STATIONS (20) ─────────────────────
            {
                'name': 'Maninagar Police Station',
                'district': 'Ahmedabad',
                'area': 'Maninagar / Kankaria',
                'latitude': 22.9985,
                'longitude': 72.6025,
                'jurisdiction': 'Maninagar, Kankaria Lake, Jawahar Chowk, Balvatika',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2546-0500',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Nikol Police Station',
                'district': 'Ahmedabad',
                'area': 'Nikol / Naroda Ring Road',
                'latitude': 23.0450,
                'longitude': 72.6680,
                'jurisdiction': 'Nikol Gam, Raspan Cross Roads, SP Ring Road East, Dehgam Rd',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2293-0700',
                'officer_capacity': 22,
                'status': 'active',
            },
            {
                'name': 'Naroda Police Station',
                'district': 'Ahmedabad',
                'area': 'Naroda / GIDC',
                'latitude': 23.0720,
                'longitude': 72.6510,
                'jurisdiction': 'Naroda GIDC Industrial Area, Bethak, Galaxy Cinema Road',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2281-0800',
                'officer_capacity': 25,
                'status': 'active',
            },
            {
                'name': 'Odhav Police Station',
                'district': 'Ahmedabad',
                'area': 'Odhav / GIDC',
                'latitude': 23.0180,
                'longitude': 72.6620,
                'jurisdiction': 'Odhav Ring Road, GIDC Estate, Express Highway Junction',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2287-0900',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Amraiwadi Police Station',
                'district': 'Ahmedabad',
                'area': 'Amraiwadi / CTM',
                'latitude': 22.9990,
                'longitude': 72.6350,
                'jurisdiction': 'CTM Cross Roads, Amraiwadi Industrial Area, Rabari Colony',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2274-1000',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Danilimda Police Station',
                'district': 'Ahmedabad',
                'area': 'Danilimda / Shah-e-Alam',
                'latitude': 22.9850,
                'longitude': 72.5800,
                'jurisdiction': 'Danilimda, Shah-e-Alam Darwaja, Chandola Lake, BRTS Corridor',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2532-1100',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Dariyapur Police Station',
                'district': 'Ahmedabad',
                'area': 'Dariyapur / Walled City',
                'latitude': 23.0330,
                'longitude': 72.5880,
                'jurisdiction': 'Dariyapur Gate, Jordan Road, Delhi Chakla',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2214-0100',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Gomtipur Police Station',
                'district': 'Ahmedabad',
                'area': 'Gomtipur / Mill Area',
                'latitude': 23.0120,
                'longitude': 72.6180,
                'jurisdiction': 'Gomtipur Darwaja, Hathijan Rd, Municipal Market East',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2216-0200',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Kalupur Police Station',
                'district': 'Ahmedabad',
                'area': 'Kalupur Railway Station',
                'latitude': 23.0270,
                'longitude': 72.5990,
                'jurisdiction': 'Ahmedabad Central Railway Station, Fruit Market, Relief Rd',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2213-0300',
                'officer_capacity': 24,
                'status': 'active',
            },
            {
                'name': 'Karanj Police Station',
                'district': 'Ahmedabad',
                'area': 'Karanj / Bhadra Fort',
                'latitude': 23.0240,
                'longitude': 72.5810,
                'jurisdiction': 'Bhadra Plaza, Lal Darwaja Bus Station, Teen Darwaja',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2550-0400',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Khadia Police Station',
                'district': 'Ahmedabad',
                'area': 'Khadia / Heritage Pols',
                'latitude': 23.0210,
                'longitude': 72.5930,
                'jurisdiction': 'Khadia Char Rasta, Mandvi ni Pol, Raipur Darwaja',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2214-0500',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Madhupura Police Station',
                'district': 'Ahmedabad',
                'area': 'Madhupura / Dudheshwar',
                'latitude': 23.0420,
                'longitude': 72.5850,
                'jurisdiction': 'Madhupura Market, Dudheshwar Water Works, Shahpur North',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2562-0600',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Rakhiyal Police Station',
                'district': 'Ahmedabad',
                'area': 'Rakhiyal / Industrial Area',
                'latitude': 23.0230,
                'longitude': 72.6310,
                'jurisdiction': 'Rakhiyal Char Rasta, Ajit Mill Compound, Saraspur East',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2274-0700',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Ramol Police Station',
                'district': 'Ahmedabad',
                'area': 'Ramol / Vastral',
                'latitude': 22.9860,
                'longitude': 72.6510,
                'jurisdiction': 'Vastral Ring Road, Ramol Gam, CTM Express Way',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2287-0800',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Sardar Nagar Police Station',
                'district': 'Ahmedabad',
                'area': 'Sardar Nagar / Hansol',
                'latitude': 23.0680,
                'longitude': 72.6150,
                'jurisdiction': 'Sardar Nagar, Noble Nagar, Hansol Bridge',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2286-0900',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Shahpur Police Station',
                'district': 'Ahmedabad',
                'area': 'Shahpur / Riverfront East',
                'latitude': 23.0360,
                'longitude': 72.5780,
                'jurisdiction': 'Shahpur Darwaja, Shankar Bhuvan, Riverfront East Division',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2560-1000',
                'officer_capacity': 16,
                'status': 'active',
            },
            {
                'name': 'Sherkotda Police Station',
                'district': 'Ahmedabad',
                'area': 'Sherkotda / Kalupur Market',
                'latitude': 23.0290,
                'longitude': 72.6080,
                'jurisdiction': 'Saraspur, Cotton Merchant Market, Railway Workshop',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2216-1100',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Bapunagar Police Station',
                'district': 'Ahmedabad',
                'area': 'Bapunagar / Diamond Market',
                'latitude': 23.0380,
                'longitude': 72.6320,
                'jurisdiction': 'Bapunagar Diamond Market, India Colony, Shyam Shikhar',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2274-1200',
                'officer_capacity': 22,
                'status': 'active',
            },
            {
                'name': 'Isanpur Police Station',
                'district': 'Ahmedabad',
                'area': 'Isanpur / Narol',
                'latitude': 22.9710,
                'longitude': 72.5950,
                'jurisdiction': 'Isanpur Circle, Govindwadi, Ghodasar, Narol Highway',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2532-1300',
                'officer_capacity': 20,
                'status': 'active',
            },
            {
                'name': 'Kagdapith Police Station',
                'district': 'Ahmedabad',
                'area': 'Kagdapith / Astodia',
                'latitude': 23.0140,
                'longitude': 72.5950,
                'jurisdiction': 'Astodia Darwaja, Gita Mandir ST Bus Stand, Kagdapith',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2535-1400',
                'officer_capacity': 22,
                'status': 'active',
            },

            # ── SOUTH & INDUSTRIAL ZONE POLICE STATIONS (8) ────────────────
            {
                'name': 'Sardar Vallabhbhai Patel Airport Police Station',
                'district': 'Ahmedabad',
                'area': 'Hansol / SVPIA Airport',
                'latitude': 23.0750,
                'longitude': 72.6280,
                'jurisdiction': 'SVPIA Terminal 1 & 2, Cargo Complex, Airport Circle',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2286-1200',
                'officer_capacity': 25,
                'status': 'active',
            },
            {
                'name': 'Vatva Police Station',
                'district': 'Ahmedabad',
                'area': 'Vatva Gam',
                'latitude': 22.9510,
                'longitude': 72.6180,
                'jurisdiction': 'Vatva Village, Rly Station Road, Bibi Lake',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2583-0100',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Vatva GIDC Police Station',
                'district': 'Ahmedabad',
                'area': 'Vatva GIDC Phase 1-4',
                'latitude': 22.9420,
                'longitude': 72.6350,
                'jurisdiction': 'Vatva GIDC Industrial Estate Phase 1 to 4, Chemical Belt',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2583-0200',
                'officer_capacity': 24,
                'status': 'active',
            },
            {
                'name': 'Aslali Police Station',
                'district': 'Ahmedabad',
                'area': 'Aslali / SP Ring Road South',
                'latitude': 22.9150,
                'longitude': 72.5850,
                'jurisdiction': 'Aslali Bypass, Bareja Highway, Kamod Circle',
                'is_cyber_specialized': False,
                'contact_number': '+91-2718-261100',
                'officer_capacity': 18,
                'status': 'active',
            },
            {
                'name': 'Narol Police Station',
                'district': 'Ahmedabad',
                'area': 'Narol / Textile Hub',
                'latitude': 22.9580,
                'longitude': 72.5980,
                'jurisdiction': 'Narol Cross Road, Lambha, Textile Cluster Estate',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2571-0300',
                'officer_capacity': 22,
                'status': 'active',
            },
            {
                'name': 'Mahila Police Station East',
                'district': 'Ahmedabad',
                'area': 'Vastral / Amraiwadi',
                'latitude': 22.9980,
                'longitude': 72.6450,
                'jurisdiction': 'East Ahmedabad Women Safety & Crisis Response Center',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2287-0400',
                'officer_capacity': 15,
                'status': 'active',
            },
            {
                'name': 'Traffic A-Division Police Station',
                'district': 'Ahmedabad',
                'area': 'Subhash Bridge / Sabarmati',
                'latitude': 23.0650,
                'longitude': 72.5810,
                'jurisdiction': 'North-West Ahmedabad Traffic Enforcement & Patrol',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2750-0100',
                'officer_capacity': 30,
                'status': 'active',
            },
            {
                'name': 'Traffic B-Division Police Station',
                'district': 'Ahmedabad',
                'area': 'Mithakhali / CG Road',
                'latitude': 23.0310,
                'longitude': 72.5620,
                'jurisdiction': 'Central-West Ahmedabad Traffic Enforcement & Escort Unit',
                'is_cyber_specialized': False,
                'contact_number': '+91-79-2640-0100',
                'officer_capacity': 30,
                'status': 'active',
            },
        ]

        created_count = 0
        updated_count = 0
        for data in stations_data:
            st, created = PoliceStation.objects.update_or_create(
                name=data['name'],
                defaults=data
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        from api.models import User
        User.objects.filter(role='admin').update(phone='1930')

        self.stdout.write(self.style.SUCCESS(
            f"Successfully seeded {created_count} new & updated {updated_count} Ahmedabad police stations (Total active in DB: {PoliceStation.objects.count()}). Central Helpline set to 1930."
        ))
